### PR TITLE
Content loaders

### PR DESCRIPTION
**Pull request by dabbott**
Changes:
Files are loaded by the new `ContentLoader` API. Containers can register themselves as loaders for specific uri schemes. (Loaders can also dynamically choose to load content based on state... not sure if we'll need this, but it's a good escape hatch, I think)

To open a file, just add a tab with id `file:///Users/.../index.ios.js`. Then the appropriate loader will spin up a container and call the actions needed to make sure the document is in the cache, etc. Everywhere outside of tabs and loaders, `id` is still just a filepath, so the changes are pretty minimal.

This is groundwork for: multiple loaders for different kinds of files. Loading non-files, e.g. search results or web pages. Load the same file with different loader, based on user choice. Split editor panes.

Other:
Renamed directory `api` => `clients`, since every file in here ends in `Client`
Created new `api` directory, for our Deco external plugin API. Added `ContentLoader` to this directory.

### CODE REVIEW

**Comment by gdowens** [comment]
can you rebase these changes? to squash commits like "mostly working" and "wip"

**Comment by gdowens** [comment]
Or just get rid of these commits in the future or something, it's not a big deal.

**Comment by dabbott** [comment]
We can just "squash and merge" when we merge

**Comment by gdowens** [comment]
The new commit name in squash and merge will be "wip mostly working working ...yada yada" right? I believe that's what those commits look like, it's a small thing.

**Pull request merged**
