### PR TITLE
Implement Show in Finder in File Tree Context Menu

### PR DESCRIPTION
**Pull request by timotius02**
As requested in  #34. Uses https://github.com/electron/electron/blob/master/docs/api/shell.md#shellshowiteminfolderfullpath. 

screen shot 2016-05-27 at 9 53 04 pm

### CODE REVIEW

**Comment by dabbott** [comment]
Awesome! Thanks for the contribution :) very helpful

**Comment by dabbott** [comment]
I think the Travis build is failing for an unrelated reason. Gonna try to fix that first, then merge this.

**Comment by timotius02** [comment]
Awesome, Thanks!

**Comment by dabbott** [comment]
Merged as https://github.com/decosoftware/deco-ide/issues/55. I rebased against master first. 

Sorry if you got a bunch of notifications. Had to fiddle with it a little to keep you as the commit author.

**Pull request closed without merging**
