### PR TITLE
In app libs

### PR DESCRIPTION
**Pull request by gdowens**

### CODE REVIEW

**Comment by dabbott** [comment]
Is this supposed to pass on Travis?

**Comment by gdowens** [comment]
It's been building for like a day I don't know wtf is going on.

**Comment by gdowens** [comment]
Just restarted, see if that does anything otherwise I'll have to look into it a bit more.

**Comment by gdowens** [comment]
I'm going to look into a potential issue with signing the package, close this, reopen and maybe that will do something.

**Pull request closed without merging**
