### PR TITLE
Update "Project" template to RN 0.27.2

### PR DESCRIPTION
**Pull request by dsibiski**
Steps required to upgrade the "Project" template:

1. Create a "temp" RN project by running `react-native init Project` somewhere outside of the `deco-ide` project
2. Run `tar -cvzf modules.tar.gz node_modules` in the "temp" project's dir.
3. Copy the `modules.tar.gz` file over to `deco-ide/desktop/deco_unpack_lib`
4. Copy over the entire contents of the temp “Project” into `deco_unpack_lib/Project`
5. Build the iOS app in Xcode (**Note**: You don’t even need to run the RN packager, we just need the binary.)
6. Open “Window > Projects” in Xcode and follow the link to the “Derived Data” for the Project. Dig down until you find the `Debug-iphonesimulator/Project.app` file.
7. Copy over the file at `deco-ide/desktop/deco_unpack_lib/Project/ios/build/Build/Products/Debug-iphonesimulator/Project.app`
8. Run `npm run copy-libs` from the `deco-ide/desktop` dir.
9. Open Deco, press "New Project"
10. Enjoy your freshly updated RN template 👍 

Addresses: https://github.com/decosoftware/deco-ide/issues/72

### CODE REVIEW

**Comment by dsibiski** [comment]
Just waiting for 0.27 to become stable so we can just update to that. If I have a chance I may update this to 0.27-rc just to make sure it all works without issue before stable is released.

**Comment by dabbott** [comment]
Sounds good. No rush. I guess it doesn't look like rnpm will make it into 0.27, since there's still activity on this https://github.com/facebook/react-native/pull/7899

**Comment by dsibiski** [comment]
@dabbott Ok, cool.

As a side note though, I'll probably also try to write a script that will automate the process I outlined above as much as possible. Updating RN should be as easy as possible to that it actually gets done on time. That's definitely one of the issues we've found with the React Native Playground. Since the process to update includes too many steps and is hard to automate, it's one of those things that just gets neglected until it's absolutely necessary.

**Comment by dabbott** [comment]
Makes sense, that'd be awesome. 

Some day, Deco should also support creating new projects for multiple versions of RN just like RN Playground. Out of scope for now though... an upgrade script is more than enough :)

**Comment by dsibiski** [comment]
New instructions (as included in the `deco-ide/project` Readme):

#### Upgrading the temporary Project template

1. Create a "temp" RN project on the latest stable release by running `react-native init Project` somewhere outside of the `deco-ide` project
2. Build the iOS app in Xcode (**Note**: You don’t even need to run the RN packager, we just need the binary.)
3. Open “Window > Projects” in Xcode and follow the link to the “Derived Data” for the Project. Dig down until you find the `Debug-iphonesimulator/Project.app` file.
4. Copy that file into the root of your "temp" RN project: ie. `~/Path/To/Project/Project.app`
5. Navigate to the `deco-ide/desktop` directory and run:
    
    ```
    npm run upgrade-project-template -- --projectPath ~/Path/To/Project
    ```
    
6. You may have to enter your password at some point during the last step.
7. Open Deco, press "New Project"
8. Enjoy your freshly updated RN template 👍

**Pull request merged**
